/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatbotContainer: typeof import('./components/ChatbotContainer.vue')['default']
    Footer: typeof import('./components/chatbot/Footer.vue')['default']
    Header: typeof import('./components/chatbot/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconChat: typeof import('./components/IconChat.vue')['default']
  }
}
